config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  root to: 'users/dashboard#index'

  namespace :admins do
    root to: 'deliveries#index'
    resources :meals, only: %i[index new edit create update destroy]
    resources :meal_sets, only: %i[index new edit create update destroy]
    resources :deliveries, only: %i[index update]
  end

  namespace :users do
    root to: 'dashboard#index'
    resources :addresses, only: %i[index new edit create update destroy]
    resource :subscription, only: %i[show new edit create update] do
      resources :deliveries, only: %i[index show new edit create update], module: :subscriptions
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # TODO: has_manyで複数契約できるようにしたい
  has_one :subscription, dependent: :destroy
  has_many :addresses, dependent: :destroy

  enumerize :shipping_zone, in: { hokkaido_okinawa: 0, others: 1 }, default: :others, predicates: true
end

app/controllers/users/addresses_controller.rb
class Users::AddressesController < Users::ApplicationController
  before_action :set_address, only: %i[edit update destroy]

  def index
    @addresses = current_user.addresses
  end

  def new
    @address = current_user.addresses.build
  end

  def create
    @address = current_user.addresses.build(address_params)
    if @address.save
      redirect_to users_addresses_path, notice: '住所を追加しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @address.update(address_params)
      redirect_to users_addresses_path, notice: '住所を更新しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @address.destroy
    redirect_to users_addresses_path, notice: '住所を削除しました'
  end

  private

  def set_address
    @address = current_user.addresses.find(params[:id])
  end

  def address_params
    # TODO: exceptにする
    params.require(:address).permit(
      :postal_code, :prefecture, :city, :street, :phone_number
    )
  end
end

app/controllers/users/application_controller.rb
class Users::ApplicationController < ApplicationController
  layout 'users/application'
  before_action :authenticate_user!
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < Users::ApplicationController
  def index
    @subscription = current_user.subscription
    @deliveries = @subscription&.deliveries&.order(delivery_date: :asc) || []
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/subscriptions/application_controller.rb
class Users::Subscriptions::ApplicationController < Users::ApplicationController
  before_action :set_subscription

  private

  def set_subscription
    @subscription = current_user.subscription
  end
end

app/controllers/users/subscriptions/deliveries_controller.rb
class Users::Subscriptions::DeliveriesController < Users::Subscriptions::ApplicationController
  before_action :set_delivery, only: %i[show edit update]

  def index
    @deliveries = @subscription.deliveries.default_order
  end

  def show
  end

  def new
    @delivery = @subscription.deliveries.build
    @delivery.delivery_meal_sets.build
  end

  def edit
    # 既存行＋足りない分をビルド
    needed = @subscription.plan.max_meal_set_count - @delivery.delivery_meal_sets.size
    needed.times { @delivery.delivery_meal_sets.build } if needed.positive?
  end

  def create
    @delivery = @subscription.deliveries.build(delivery_params)
    if @delivery.save
      redirect_to users_root_path, notice: '配送を作成しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @delivery.update(delivery_params)
      redirect_to users_root_path, notice: '配送を更新しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_delivery
    @delivery = current_user.subscription.deliveries.find(params[:id])
  end

  def delivery_params
    params.require(:delivery).permit(
      :delivery_date, :time_slot, :address_id,
      delivery_meal_sets_attributes: %i[id meal_set_id quantity _destroy]
    )
  end
end

app/controllers/users/subscriptions_controller.rb
class Users::SubscriptionsController < Users::ApplicationController
  before_action :set_subscription, only: %i[show edit update]

  def show
  end

  def new
    @subscription = current_user.build_subscription
  end

  def edit
    @subscription = current_user.subscription
  end

  def create
    @subscription = current_user.build_subscription(subscription_params)
    if @subscription.save
      redirect_to users_root_path, notice: 'プランを設定しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @subscription.update(subscription_params)
      redirect_to users_root_path, notice: '契約内容を更新しました'
    else
      render :edit
    end
  end

  private

  def set_subscription
    @subscription = current_user.subscription
  end

  def subscription_params
    # TODO: paused_atも保存できるように
    params.require(:subscription).permit(:plan_id, :frequency)
  end
end

app/views/users/addresses/_form.html.haml
= simple_form_for [:users, address] do |f|
  .row.mb-3
    .col-md-6
      = f.input :postal_code, label: '郵便番号', required: true, input_html: { class: 'form-control' }
    .col-md-6
      = f.input :phone_number, label: '電話番号', required: true, input_html: { class: 'form-control' }

  .row.mb-3
    .col-md-4
      = f.input :prefecture, label: '都道府県', required: true, input_html: { class: 'form-control' }
    .col-md-4
      = f.input :city, label: '市区町村', required: true, input_html: { class: 'form-control' }
    .col-md-4
      = f.input :street, label: '番地', required: true, input_html: { class: 'form-control' }

  .d-flex.justify-content-end.mt-4
    = f.button :submit, '保存', class: 'btn btn-primary px-4 py-2'

app/views/users/addresses/edit.html.haml
.container.mt-4
  .card.shadow-sm
    .card-header.bg-light
      %h2.mb-0= action_name == 'new' ? '新規住所追加' : '住所編集'
    .card-body
      = render 'form', address: @address

  = link_to '住所一覧へ戻る', users_addresses_path, class: 'btn btn-link mt-3'

app/views/users/addresses/index.html.haml
.container.mt-4
  .d-flex.justify-content-between.align-items-center.mb-3
    %h1.mb-0 住所一覧
    = link_to '新規住所追加', new_users_address_path, class: 'btn btn-primary'

  .card.shadow-sm
    .card-body.p-0
      %table.table.table-hover.mb-0
        %thead
          %tr
            %th 郵便番号
            %th 都道府県
            %th 市区町村
            %th 番地
            %th 電話番号
            %th.text-center 操作
        %tbody
          - @addresses.each do |address|
            %tr
              %td= address.postal_code
              %td= address.prefecture
              %td= address.city
              %td= address.street
              %td= address.phone_number
              %td.text-center
                = link_to '編集', edit_users_address_path(address), class: 'btn btn-sm btn-outline-secondary me-2'
                = link_to '削除', users_address_path(address), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-sm btn-outline-danger'

app/views/users/addresses/new.html.haml
.container.mt-4
  .card.shadow-sm
    .card-header.bg-light
      %h2.mb-0= action_name == 'new' ? '新規住所追加' : '住所編集'
    .card-body
      = render 'form', address: @address

  = link_to '住所一覧へ戻る', users_addresses_path, class: 'btn btn-link mt-3'