config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  root to: 'users/dashboard#index'

  namespace :admins do
    root to: 'deliveries#index'
    resources :meals, only: %i[index new edit create update destroy]
    resources :meal_sets, only: %i[index new edit create update destroy]
    resources :deliveries, only: %i[index update]
  end

  namespace :users do
    root to: 'dashboard#index'
    resources :addresses, only: %i[index new edit create update destroy]
    resource :subscription, only: %i[show new edit create update] do
      resources :deliveries, only: %i[index show new edit create update], module: :subscriptions
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/meal_set.rb
class MealSet < ApplicationRecord
  has_one_attached :thumbnail do |attachable|
    attachable.variant :thumb, resize_to_limit: [200, 200]
  end

  has_many :meal_set_items, dependent: :destroy
  has_many :meals, through: :meal_set_items
  has_many :delivery_meal_sets, dependent: :destroy
  has_many :deliveries, through: :delivery_meal_sets

  accepts_nested_attributes_for :meal_set_items, allow_destroy: true

  validates :name, presence: true
  validates :thumbnail, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..(20.megabytes) }

  scope :default_order, -> { order(:id, :name) }
end

app/controllers/admins/meal_sets_controller.rb
class Admins::MealSetsController < Admins::ApplicationController
  before_action :set_meal_set, only: %i[show edit update destroy]

  def index
    @meal_sets = MealSet.all.order(:id)
  end

  def show
  end

  def new
    @meal_set = MealSet.new
    # TODO: 初期値は一番上の食材を固定. modelに書きたい
    @meal_set.meal_set_items.build(meal: Meal.default_order.first)
  end

  def create
    @meal_set = MealSet.new(meal_set_params)
    if @meal_set.save
      redirect_to admins_meal_sets_path(@meal_set), notice: '食材セットを登録しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # TODO: 微妙
    if @meal_set.meal_set_items.empty?
      @meal_set.meal_set_items.build
    end
  end

  def update
    if @meal_set.update(meal_set_params)
      redirect_to admins_meal_sets_path(@meal_set), notice: '食材セットを更新しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @meal_set.destroy
    redirect_to admins_meal_sets_path, notice: '食材セットを削除しました'
  end

  private

  def set_meal_set
    @meal_set = MealSet.find(params[:id])
  end

  def meal_set_params
    # TODO: rails8のexceptにしたい
    params.require(:meal_set).permit(
      :name,
      :description,
      :thumbnail,
      meal_set_items_attributes: %i[id meal_id quantity _destroy]
    )
  end
end

app/views/admins/meal_sets/_form.html.haml
= f.input :name,
          autofocus: true,
          required: true
= f.input :description,
          required: true
= f.input :thumbnail,
          as: :file

%h3 品目
-# TODO: 品目を追加・削除できるように
= f.simple_fields_for :meal_set_items do |ff|
  .item-row
    = ff.input :meal_id,
               collection: Meal.default_order,
               prompt: '食材を選択',
               label: '食材'
    = ff.input :quantity

app/views/admins/meal_sets/edit.html.haml
.container.mt-4
  %h1.mb-4 食材セット編集
  = simple_form_for @meal_set, url: admins_meal_set_path(@meal_set), method: :patch do |f|
    = render 'form', f: f, meal_set: @meal_set
    .mt-4.d-flex.justify-content-end
      = f.button :submit, '更新する', class: 'btn btn-primary'
  = link_to '一覧に戻る', admins_meal_sets_path(@meal_set), class: 'btn btn-secondary mt-3'

app/views/admins/meal_sets/index.html.haml
.container.mt-4
  %h1.mb-4 食材セット一覧

  .mb-3
    = link_to '食材セット登録', new_admins_meal_set_path, class: 'btn btn-primary'
    = link_to '食材一覧', admins_meals_path, class: 'btn btn-link'

  %table.table.table-striped
    %thead
      %tr
        %th セット名
        %th
    %tbody
      - @meal_sets.each do |meal_set|
        %tr
          %td= meal_set.name
          %td.d-flex.gap-2
            -# TODO: 詳細に遷移させる
            = link_to 'セット詳細', admins_meal_set_path(meal_set), class: 'btn btn-sm'
            = link_to '編集', edit_admins_meal_set_path(meal_set), class: 'btn btn-sm'

  = link_to 'ダッシュボードに戻る', admins_root_path, class: 'btn btn-link mt-3'

app/views/admins/meal_sets/new.html.haml
.container.mt-4
  %h1.mb-4 食材セット登録
  = simple_form_for @meal_set, url: admins_meal_sets_path do |f|
    = render 'form', f: f, meal_set: @meal_set
    .mt-4.d-flex.justify-content-end
      = f.button :submit, '登録する', class: 'btn btn-primary'
  = link_to '一覧に戻る', admins_meal_sets_path(@meal_set), class: 'btn btn-link mt-3'

app/views/admins/meal_sets/show.html.haml
.container.mt-4
  %h1.mb-4 食材セット詳細

  %dl.row
    %dt.col-sm-3 セット名
    %dd.col-sm-9= @meal_set.name

    %dt.col-sm-3 価格（税抜）
    %dd.col-sm-9= number_to_currency(@meal_set.price, unit: '¥', precision: 0)

    %dt.col-sm-3 同梱アイテム
    %dd.col-sm-9= simple_format(@meal_set.included_items)

    %dt.col-sm-3 重量(kg)
    %dd.col-sm-9= @meal_set.weight

    %dt.col-sm-3 冷蔵品
    %dd.col-sm-9= @meal_set.refrigerated? ? 'あり' : 'なし'

    %dt.col-sm-3 アレルギー情報
    %dd.col-sm-9= simple_format(@meal_set.allergy_info)

    %dt.col-sm-3 レシピPDF
    %dd.col-sm-9

  .mt-4.d-flex.justify-content-end
    = link_to '編集',
              edit_admins_meal_set_path(@meal_set),
              class: 'btn btn-primary me-2'