config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  root to: 'users/dashboard#index'

  namespace :admins do
    root to: 'deliveries#index'
    resources :meals, only: %i[index new edit create update destroy]
    resources :meal_sets, only: %i[index new edit create update destroy]
    resources :deliveries, only: %i[index update]
  end

  namespace :users do
    root to: 'dashboard#index'
    resources :addresses, only: %i[index new edit create update destroy]
    resource :subscription, only: %i[show new edit create update] do
      resources :deliveries, only: %i[index show new edit create update], module: :subscriptions
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :meal_set_items, dependent: :destroy

  scope :default_order, -> { order(:id) }
end

app/controllers/admins/meals_controller.rb
class Admins::MealsController < Admins::ApplicationController
  before_action :set_meal, only: %i[edit update destroy]

  def index
    @meals = Meal.default_order
  end

  def new
    @meal = Meal.new
  end

  def edit; end;

  def create
    @meal = Meal.new(meal_params)
    if @meal.save
      redirect_to admins_meals_path, notice: '食材を作成しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @meal.update(meal_params)
      redirect_to admins_meals_path, notice: '食材を更新しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @meal.destroy!
    redirect_to meals_path, notice: '食材を削除しました'
  end

  private

  def set_meal
    @meal = Meal.find(params[:id])
  end

  def meal_params
    params.expect(meal: %i[name refrigeration])
  end
end

app/views/admins/meals/_form.html.haml
= f.input :name,
          autofocus: true,
          required: true
= f.input :refrigeration,
          as: :boolean

app/views/admins/meals/edit.html.haml
.container.mt-4
  %h1.mb-4 食材登録
  = simple_form_for @meal, url: admins_meal_path(@meal), method: :patch do |f|
    = render 'form', f: f, meal: @meal
    .mt-4.d-flex.justify-content-end
      = f.button :submit, '更新する', class: 'btn btn-primary'
  = link_to '一覧に戻る', admins_root_path, class: 'btn btn-link mt-3'

app/views/admins/meals/index.html.haml
.container.mt-4
  %h1.mb-4 食材一覧

  .mb-3
    = link_to '食材登録', new_admins_meal_path, class: 'btn btn-primary'
    = link_to '食材セット一覧', admins_meal_sets_path, class: 'btn btn-link'

  %table.table
    %thead
      %tr
        %th ID
        %th 名前
        %th 凍結品
        %th
    %tbody
      - @meals.each do |meal|
        %tr
          %td= meal.id
          %td= meal.name
          %td= meal.refrigeration? ? 'はい' : 'いいえ'
          %td
            = link_to '編集', edit_admins_meal_path(meal), class: 'btn btn-secondary btn-sm'
            = link_to '削除', admins_meal_path(meal), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger btn-sm'

app/views/admins/meals/new.html.haml
.container.mt-4
  %h1.mb-4 食材登録
  = simple_form_for @meal, url: admins_meals_path do |f|
    = render 'form', f: f, meal: @meal
    .mt-4.d-flex.justify-content-end
      = f.button :submit, '更新する', class: 'btn btn-primary'
  = link_to '一覧に戻る', admins_root_path, class: 'btn btn-link mt-3'