config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  root to: 'users/dashboard#index'

  namespace :admins do
    root to: 'deliveries#index'
    resources :meals, only: %i[index new edit create update destroy]
    resources :meal_sets, only: %i[index new edit create update destroy]
    resources :deliveries, only: %i[index update]
  end

  namespace :users do
    root to: 'dashboard#index'
    resources :addresses, only: %i[index new edit create update destroy]
    resource :subscription, only: %i[show new edit create update] do
      resources :deliveries, only: %i[index show new edit create update], module: :subscriptions
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/views/layouts/admins/_topbar.html.haml
%nav.bg-secondary.navbar.navbar-expand-lg.p-4{ data: { bs_theme: 'dark' } }
  .container-fluid
    = link_to '定期食材配信サービス(管理者)', admins_root_path, class: 'navbar-brand'
    .d-flex.justify-content-between.w-100
      %ul.navbar-nav
        %li.nav-item
          = link_to '食材セット一覧', admins_meal_sets_path, class: 'nav-link'
      %ul.navbar-nav
        %li.nav-item
          = button_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link'

app/views/layouts/admins/application.html.haml
!!!
%html
  %head
    %meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %title MatchingServices
    %meta{content: 'width=device-width,initial-scale=1', name: 'viewport'}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
  %body
    = render 'layouts/admins/topbar'
    - if notice.present? || alert.present?
      = render 'partial/flash'
    = yield